[TASK] Add the new @lazy annotation
oliverklee/ext-oelib pull request #484
Opened 2020-12-01 08:14 UTC by Konafets

Closes #468

2020-12-01 09:35 UTC, oliverklee requested changes

2020-12-01 09:35 UTC, oliverklee commented on Tests/Unit/Domain/Fixtures/ParentModel.php
> +     * @TYPO3\CMS\Extbase\Annotation\ORM\Lazy
Please let's `use` this class, and please lets have this annotation before the old `@lazy`.

2020-12-05 16:48 UTC, Konafets commented on Tests/Unit/Domain/Fixtures/ParentModel.php
> +     * @TYPO3\CMS\Extbase\Annotation\ORM\Lazy
Does this work w/o the FQNS?

2020-12-05 16:54 UTC, oliverklee commented on Tests/Unit/Domain/Fixtures/ParentModel.php
> +     * @TYPO3\CMS\Extbase\Annotation\ORM\Lazy
Yes, it does. https://git.higidi.com/TYPO3/TYPO3.CMS/commit/0b3eb3664cc59eb12ab3cae6b737f443ba2a32b6:

> Doctrine annotations are actual defined classes, therefore you can also use the annotation with a use statement.

2020-12-05 16:59 UTC, oliverklee approved these changes

2020-12-05 16:59 UTC, merged