[CLEANUP] Update the configuration proxy to the new configuration format
oliverklee/ext-oelib pull request #506
Opened 2020-12-06 16:27 UTC by Konafets

Closes #465

2020-12-06 16:29 UTC, Konafets commented
How would you add a `@deprecate` flag to the old way as you request in the issue?

2020-12-06 17:04 UTC, oliverklee requested changes

2020-12-06 17:04 UTC, oliverklee commented on Classes/Templating/TemplateHelper.php
> +        return ConfigurationCheck::class;
Please undo the changes to this file. They are not related to the issue to be solved, and they are required for configuration check to work on extensions like seminars 3.x that still rely on the configuration check by class name.

2020-12-06 17:13 UTC, oliverklee commented on Classes/Configuration/ConfigurationProxy.php
> +    private function hasNewConfigurationFormat(): bool
Please also mark both functions as deprecated and to be removed in oelib 4.0 as we'll drop support for the old way after dropping support for TYPO3 8.7.

2020-12-06 17:14 UTC, oliverklee commented
> How would you add a `@deprecate` flag to the old way as you request in the issue?

We can deprecate the new methods (and add a comment that only the new way will be supported in oelib 4.0).

2020-12-06 17:15 UTC, oliverklee commented
This also needs a changelog entry.

2020-12-07 17:44 UTC, oliverklee approved these changes

2020-12-07 17:44 UTC, merged