[CLEANUP] Stop using tmpl->getFileName
oliverklee/ext-oelib pull request #512
Opened 2020-12-12 18:08 UTC by Konafets

Closes #470

2020-12-12 18:16 UTC, Konafets commented
Will fix this one later.

2020-12-12 18:17 UTC, oliverklee requested changes

2020-12-12 18:17 UTC, oliverklee commented on Classes/Configuration/ConfigurationCheck.php
> +     * @var FilePathSanitizer $filePathSanitizer
The variable name should not be here in the annotation. It's only required for local variables, not for properties.

2020-12-12 18:17 UTC, oliverklee commented on Classes/Configuration/ConfigurationCheck.php
> +            $fileName = $this->filePathSanitizer->sanitize($fileName);
The local variable `$frontEndController` then is not needed anymore.

2020-12-12 18:17 UTC, oliverklee commented on Classes/Configuration/ConfigurationCheck.php
> +
Please let*s drop this blank line here:

2020-12-12 18:17 UTC, oliverklee commented on Classes/Configuration/ConfigurationCheck.php
> +            $file = $this->filePathSanitizer->sanitize($rawFileName);
We then also do not need the null check for the FE controller a few lines up.

2020-12-12 18:17 UTC, oliverklee commented on Classes/Templating/TemplateHelper.php
> +            $templateFileName = GeneralUtility::makeInstance(FilePathSanitizer::class)->sanitize($templateFileName);
Please let's put the sanitizer in  a local variable so it can have an `@var` annotation.

2020-12-12 18:28 UTC, oliverklee requested changes
These changes seem to need version checks for 8/9.

2020-12-12 21:27 UTC, oliverklee requested changes
Some of the older comments also are not addressed yet.

2020-12-12 21:27 UTC, oliverklee commented on Classes/Configuration/ConfigurationCheck.php
> +                $file = GeneralUtility::makeInstance(\TYPO3\CMS\Frontend\Resource\FilePathSanitizer::class)
Please `use` the class.

2020-12-12 21:27 UTC, oliverklee commented on Classes/Templating/TemplateHelper.php
> +                $templateFileName = GeneralUtility::makeInstance(\TYPO3\CMS\Frontend\Resource\FilePathSanitizer::class)
Please `use` the class.

2020-12-13 15:48 UTC, oliverklee approved these changes

2020-12-13 15:48 UTC, merged